import logging

from fastapi import APIRouter, HTTPException

from socialapi.database import comment_table, database, post_table
from socialapi.models.post import (
    Comment,
    CommentIn,
    UserPost,
    UserPostIn,
    UserPostWithComments,
)

router = APIRouter()

# Configure logging
logger = logging.getLogger(__name__)

# Temporary in-memory storage
# posts_table = {}
# comments_table = {}


async def find_post(post_id: int):
    query = post_table.select().where(post_table.c.id == post_id)
    # Log the query
    logger.debug(
        f"Finding post with ID: {post_id}"
    )  # Be careful with logging sensitive info
    return await database.fetch_one(query)


@router.post("/post", response_model=UserPost, status_code=201)
async def create_post(post: UserPostIn):
    data = post.model_dump()  # Use "post.dict()" for Pydantic v1
    query = post_table.insert().values(data)

    # Log the query
    logger.debug(f"Executing query: {query}")

    last_record_id = await database.execute(query)  # ID generated by the database
    return {
        **data,
        "id": last_record_id,
    }  # The ** unpacks the data dictionary into key-value pairs


@router.get("/post", response_model=list[UserPost])  # List of posts
async def get_all_posts():
    query = post_table.select()

    # log the query
    logger.debug(f"Executing query: {query}")

    return await database.fetch_all(query)


# ---- Comments -----
@router.post("/comment", response_model=Comment, status_code=201)
async def create_comment(comment: CommentIn):
    # Validate that the post exists
    post = await find_post(comment.post_id)
    if not post:
        raise HTTPException(status_code=404, detail="Post not found")

    data = comment.model_dump()
    query = comment_table.insert().values(data)
    last_record_id = await database.execute(query)
    return {**data, "id": last_record_id}


@router.get("/post/{post_id}/comments", response_model=list[Comment])
# pydantic detects the post_id from the path
async def get_comments_on_post(post_id: int):
    post = await find_post(post_id)
    if not post:
        raise HTTPException(status_code=404, detail="Post not found")
    query = comment_table.select().where(comment_table.c.post_id == post_id)

    # Log the query
    logger.debug(f"Executing query: {query}")
    return await database.fetch_all(query)


@router.get("/post/{post_id}", response_model=UserPostWithComments)
async def get_post_with_comments(post_id: int):
    post = await find_post(post_id)
    if not post:
        raise HTTPException(status_code=404, detail="Post not found")

    # The output must match the UserPostWithComments model
    return {
        "post": post,
        "comments": await get_comments_on_post(post_id),
    }
